### PR TITLE
Improve handling inflections

### PR DESCRIPTION
**Pull request by be5invis**

### CODE REVIEW

**Comment by puzrin** [comment]
Should fix #1 (for reference)
- it worth to keep fomatting intact. It was done such way intentionally, to make equtions more readable. Also formattings change + code change in one place make more difficult to understand code.
- reasons to export `_cubicToQuad`?
- `ts` not clear by name what is this

**Comment by be5invis** [comment]
@puzrin The test assumes that the `t` values used for segmentation is uniform, but if there is an inflection, then the segmentation is non-uniform, and the array `ts` is used for it.

**Comment by puzrin** [comment]
Also make sure:
- benchmark does not show serious regression
- test case from issue #1 added
- remove .esformatter

**Comment by be5invis** [comment]
@puzrin done.

**Comment by puzrin** [comment]
@be5invis we reviewed existing code with @a-rodin , and it seems that math should cover inflection case https://github.com/fontello/cubic2quad/blob/1.0.0/index.js#L103

Our assumption is that problem can be with attempts to compare float values with 0, instead of checking small "epsilon" range:
- https://github.com/fontello/cubic2quad/blob/master/index.js#L67
- https://github.com/fontello/cubic2quad/blob/master/index.js#L73
- https://github.com/fontello/cubic2quad/blob/master/index.js#L86
- https://github.com/fontello/cubic2quad/blob/master/index.js#L99

Also (if steps above will not help)
- number of points in error check can be increased https://github.com/fontello/cubic2quad/blob/master/index.js#L203
- line check epsilon can be increased https://github.com/fontello/cubic2quad/blob/master/index.js#L178

I've sheduled to dig this issue next week.

**Comment by be5invis** [comment]
@puzrin My PR manually adds on-curve points at inflections exactly, and in `processSegment`, use ray intersection instead of line intersection, which avoids producing an inflection when approximating a "small" segment.

**Comment by puzrin** [comment]
@be5invis could you join all your commits into one and remove everything not related to math update (esformatter config + formatting change). That will simplify code check.

I see what you did, but suspect that solution could be more simple (that's only my personal assumption). Next week we will check if it's possible. If not - will fallback to your approach.

**Comment by be5invis** [comment]
@puzrin Fine :)

**Comment by be5invis** [comment]
@puzrin Any progress?

**Comment by puzrin** [comment]
Probably, today. This task is still marked with high priority, but me and my programmers are a bit busy with other things.

**Comment by puzrin** [comment]
Close in favour of https://github.com/fontello/cubic2quad/commit/83233c7d33a1d0d6e25dcd6efecb2ad18a01b1fa

**Pull request closed without merging**
